export const vehicles = [
  {
    _id: '1',
    make: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2022,
    price: 54000,
    mileage: 12000,
    image: '/images/mercedes-benz-c-class.jpg',
    color: 'Obsidian Black',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    description: 'Pure luxury in a compact sedan. Features a stunning digital cockpit, premium materials, and unparalleled comfort for an executive driving experience.',
    features: [],
  },
  {
    _id: '2',
    make: 'Audi',
    model: 'A4',
    year: 2023,
    price: 49500,
    mileage: 7000,
    image: '/images/audi-a4.jpg',
    color: 'Navarra Blue',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    description: 'Sophistication and performance in one package. Features Audi\'s legendary Quattro all-wheel drive for superior handling in all conditions.',
    features: [],
  },
  {
    _id: '3',
    make: 'BMW',
    model: '3 Series',
    year: 2021,
    price: 41000,
    mileage: 31000,
    image: '/images/bmw-3-series.jpg',
    color: 'Portimao Blue',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    description: 'The ultimate driving machine. A perfect blend of luxury, sporty performance, and cutting-edge technology that defines the modern sports sedan.',
    features: [],
  },
  {
    _id: '4',
    make: 'Ford',
    model: 'F-150 Lightning',
    year: 2022,
    price: 65000,
    mileage: 11000,
    image: '/images/ford-f150.jpg',
    color: 'Iconic Silver',
    transmission: 'Automatic',
    fuelType: 'Electric',
    description: 'The future of trucks is here. All-electric power with incredible torque, a massive front trunk, and the capability you expect from an F-150.',
    features: [],
  },
  {
    _id: '5',
    make: 'Ford',
    model: 'Mustang',
    year: 2023,
    price: 48000,
    mileage: 5000,
    image: '/images/ford-mustang.jpg',
    color: 'Race Red',
    transmission: 'Manual',
    fuelType: 'Gasoline',
    description: 'An iconic American muscle car with thrilling performance and a head-turning design. The V8 engine provides an unforgettable driving experience.',
    features: [],
  },
  {
    _id: '6',
    make: 'Mazda',
    model: 'RX-7',
    year: 1999,
    price: 55000,
    mileage: 68000,
    image: '/images/mazda-rx7.jpg',
    color: 'Brilliant Black',
    transmission: 'Manual',
    fuelType: 'Gasoline',
    description: 'A legendary JDM sports car featuring a unique twin-turbo rotary engine. A true icon of design and performance for the driving enthusiast.',
    features: [],
  },
  {
    _id: '7',
    make: 'Honda',
    model: 'Civic',
    year: 2023,
    price: 26000,
    mileage: 9000,
    image: '/images/honda-civic.jpg',
    color: 'Rallye Red',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    description: 'A compact car that sets the standard for fun, efficiency, and reliability. Loaded with modern tech and advanced safety features.',
    features: [],
  },
  {
    _id: '8',
    make: 'Honda',
    model: 'CR-V',
    year: 2023,
    price: 34000,
    mileage: 12000,
    image: '/images/honda-crv.jpg',
    color: 'Canyon River Blue',
    transmission: 'Automatic',
    fuelType: 'Hybrid',
    description: 'A versatile and efficient hybrid SUV. Plenty of cargo space and advanced safety features make it a top choice for families.',
    features: [],
  },
  {
    _id: '9',
    make: 'Jeep',
    model: 'Wrangler',
    year: 2022,
    price: 43000,
    mileage: 19000,
    image: '/images/jeep-wrangler.jpg',
    color: 'Firecracker Red',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    description: 'The ultimate off-road vehicle. Ready for any adventure with its rugged build, removable top, and iconic design.',
    features: [],
  },
  {
    _id: '10',
    make: 'Toyota',
    model: 'RAV4',
    year: 2022,
    price: 31000,
    mileage: 18000,
    image: '/images/toyota-rav4.jpg',
    color: 'Lunar Rock',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    description: 'A popular and reliable compact SUV. Great for city driving and weekend adventures, with excellent fuel economy.',
    features: [],
  },
  {
    _id: '11',
    make: 'Tesla',
    model: 'Model 3',
    year: 2021,
    price: 38000,
    mileage: 35000,
    image: '/images/tesla-model3.jpg',
    color: 'Solid Black',
    transmission: 'Automatic',
    fuelType: 'Electric',
    description: 'Experience the future of driving with this all-electric sedan. Instant acceleration and a minimalist interior.',
    features: [],
  },
  {
    _id: '12',
    make: 'Toyota',
    model: 'Camry',
    year: 2023,
    price: 32500,
    mileage: 15000,
    image: '/images/toyota-camry.jpg',
    color: 'Ice Edge',
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    description: 'A reliable and stylish sedan known for its smooth ride and fuel efficiency. Perfect for daily commutes and family trips.',
    features: [],
  },
  {
    _id: '13',
    make: 'Chevrolet',
    model: 'Silverado',
    year: 2022,
    price: 47500,
    mileage: 22000,
    image: '/images/chevrolet-silverado.jpg',
    color: 'Northsky Blue',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    description: 'A heavy-duty truck built for the toughest jobs. Impressive towing capacity and a comfortable, spacious cabin.',
    features: [],
  },
];
